language: node_js
  node_js:
    - "v12.16.0"
branches:
  only:
    - develop
before_install:
  - export TZ='Asia/Shanghai'
install:
  - npm install -g gitbook-cli
  - gitbook install
script:
  - gitbook build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: 7900f72dc644b9bdd6dfb0fe072480a4a20a936c 
  local-dir: ./_book/ 
  target-branch: gh-pages
  verbose: true