# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    steps:
    # checkout
    - uses: actions/checkout@v2
    # language
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    # gitbook
    - name: gitbook
       run: npm install -g gitbook-cli
       run: gitbook install
       run: gitbook build

    # push 
    - name: Push GitBook
      working-directory: ./_book
        run: |
          pwd
